### ISSUE TITLE
Source of es_api_get_index_by_args()

### ISSUE THREAD

**Issue by kasparsd** [Automattic/wpes-lib#2]
`es_api_bulk_index()` uses`es_api_get_index_by_args()` which isn't defined anywhere. Could you please add that method to the `es-api.php` example?

**Comment by gibrown** [comment]
Sorry, this got a bit buried in my inbox...

That function becomes a bit convoluted which is why I left it out. We maintain a table with all of our indices that does a lookup for the index name based off of 'name', 'version', and 'blog_id'. It returns the best index based off of those values which includes the index name, the cluster name, and the doc builder class names for that particular index.
